version: "3.7"

services:
  deniz:
    image: "php:7.0-apache"
    container_name: "deniz"
    hostname: "whoami"
    volumes:
      - ./src:/var/www/html
    ports:
      - 8000:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.rule=Host(`$MY_DOMAIN`)"
      - "traefik.http.routers.whoami.tls.certresolver=lets-encr"

networks:
  default:
    external:
      name: $DEFAULT_NETWORK